import type { MerchantStorefrontProduct } from "@/types/merchant-storefront";

export const mockStorefrontProducts: MerchantStorefrontProduct[] = [
  {
    id: "preview-p1",
    name: "Vitamin C Face Serum",
    description: "Brightening serum with vitamin C and hyaluronic acid.",
    price: 120,
    salePrice: 99,
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&h=800&fit=crop"],
    categoryId: "Skincare",
    inStock: true,
    featured: true,
  },
  {
    id: "preview-p2",
    name: "Shea Butter Body Cream",
    description: "Rich, moisturizing body cream with natural shea butter.",
    price: 85,
    images: ["https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&h=800&fit=crop"],
    categoryId: "Body",
    inStock: true,
    featured: true,
  },
  {
    id: "preview-p3",
    name: "Aloe Vera Soothing Gel",
    description: "Cooling and hydrating gel for sun-exposed skin.",
    price: 65,
    images: ["https://images.unsplash.com/photo-1601049676869-702ea24cfd58?w=800&h=800&fit=crop"],
    categoryId: "Skincare",
    inStock: true,
    featured: true,
  },
  {
    id: "preview-p4",
    name: "Lip Glow Kit",
    description: "Complete lip care set with natural oils and butters.",
    price: 150,
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&h=800&fit=crop"],
    categoryId: "Cosmetics",
    inStock: true,
    featured: true,
  },
  {
    id: "preview-p5",
    name: "Charcoal Detox Face Mask",
    description: "Deep cleansing mask with activated charcoal.",
    price: 95,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=800&fit=crop"],
    categoryId: "Skincare",
    inStock: false,
    featured: false,
  },
  {
    id: "preview-p6",
    name: "Coconut Oil Hair Food",
    description: "Nourishing hair treatment with coconut and castor oil.",
    price: 70,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=800&fit=crop"],
    categoryId: "Hair",
    inStock: true,
    featured: false,
  },
];