// lib/merchant/wallet/wallet-labels.ts
//
// Public merchant re-exports over the shared labels module. Old names
// that the merchant tree already imports are aliased to the shared
// names.

export {
  MERCHANT_WALLET_TYPE_LABEL as WALLET_TYPE_LABEL,
  MERCHANT_WALLET_TYPE_DESCRIPTION as WALLET_TYPE_DESCRIPTION,
  MERCHANT_FUNDING_STATUS_LABEL as FUNDING_STATUS_LABEL,
  MERCHANT_FUNDING_STATUS_VARIANT as FUNDING_STATUS_VARIANT,
  MERCHANT_WITHDRAWAL_STATUS_LABEL as WITHDRAWAL_STATUS_LABEL,
  MERCHANT_WITHDRAWAL_STATUS_VARIANT as WITHDRAWAL_STATUS_VARIANT,
  MERCHANT_LEDGER_KIND_LABEL as LEDGER_KIND_LABEL,
  MERCHANT_LEDGER_KIND_VARIANT as LEDGER_KIND_VARIANT,
  MERCHANT_FUNDING_METHOD_LABEL as FUNDING_METHOD_LABEL,
  MERCHANT_FUNDING_METHOD_DESCRIPTION as FUNDING_METHOD_DESCRIPTION,
  MERCHANT_APPROVAL_REASON_LABEL as APPROVAL_REASON_LABEL,
  MERCHANT_APPROVAL_REASON_VARIANT as APPROVAL_REASON_VARIANT,
  MERCHANT_WITHDRAWAL_FAILURE_LABEL as WITHDRAWAL_FAILURE_LABEL,
  MERCHANT_AUTO_PAY_SOURCE_LABEL as AUTO_PAY_SOURCE_LABEL,
  MERCHANT_AUTO_PAY_SOURCE_DESCRIPTION as AUTO_PAY_SOURCE_DESCRIPTION,
  describeMerchantSource as describeSource,
  describeMerchantDestination as describeDestination,
  toneForMerchantDelta as toneForDelta,
} from "@/lib/domains/wallet/merchant-money/labels";

export function maskSourceLabel(
  provider: string,
  maskedLabel: string
): string {
  return provider + " " + maskedLabel;
}