// lib/domains/subscriptions/seed.ts

import type { SubscriptionPlan } from "./types";

export function seedSubscriptionPlans(): SubscriptionPlan[] {
  return [
    {
      code: "starter",
      name: "Starter",
      description: "For merchants testing the waters.",
      monthlyPriceGHS: 50,
      annualPriceGHS: 500,
      maxProducts: 20,
      themes: ["studio"],
      paymentMethods: ["momo"],
      subdomain: true,
      customDomain: false,
      supportTier: "email",
      featureFlags: {},
      aiAssistant: false,
      visibility: "public",
      sortOrder: 1,
      highlighted: false,
    },
    {
      code: "growth",
      name: "Growth",
      description: "For merchants ready to scale.",
      monthlyPriceGHS: 150,
      annualPriceGHS: 1500,
      maxProducts: 200,
      themes: ["studio", "editorial"],
      paymentMethods: ["momo", "card"],
      subdomain: true,
      customDomain: true,
      supportTier: "priority_email",
      featureFlags: {},
      aiAssistant: true,
      visibility: "public",
      sortOrder: 2,
      highlighted: false,
    },
    {
      code: "pro",
      name: "Pro",
      description: "For merchants running a serious operation.",
      monthlyPriceGHS: 400,
      annualPriceGHS: 4000,
      maxProducts: "unlimited",
      themes: ["airy", "editorial", "studio"],
      paymentMethods: ["momo", "card", "bank"],
      subdomain: true,
      customDomain: true,
      supportTier: "chat",
      featureFlags: {},
      aiAssistant: true,
      visibility: "public",
      sortOrder: 3,
      highlighted: true,
    },
    {
      code: "enterprise",
      name: "Enterprise",
      description: "Bespoke terms, contracts, and support.",
      monthlyPriceGHS: "custom",
      annualPriceGHS: "custom",
      maxProducts: "unlimited",
      themes: ["airy", "editorial", "studio", "statement"],
      paymentMethods: ["momo", "card", "bank", "wallet"],
      subdomain: true,
      customDomain: true,
      supportTier: "dedicated",
      featureFlags: {},
      aiAssistant: true,
      visibility: "public",
      sortOrder: 4,
      highlighted: false,
    },
  ];
}