import { ALL_PERMISSIONS, PERMISSIONS, type Permission } from "./permissions";

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  OPERATIONS_ADMIN: "operations_admin",
  FINANCE_ADMIN: "finance_admin",
  SUPPORT_ADMIN: "support_admin",
  SERVICE_ADMIN: "service_admin",
  ANALYST: "analyst",
  VIEWER: "viewer",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export interface RoleDefinition {
  value: Role;
  label: string;
  description: string;
}

export const ALL_ROLES: RoleDefinition[] = [
  {
    value: ROLES.SUPER_ADMIN,
    label: "Super Admin",
    description: "Unrestricted access to every part of the admin centre.",
  },
  {
    value: ROLES.OPERATIONS_ADMIN,
    label: "Operations Admin",
    description:
      "Runs the day-to-day: orders, providers, services, storefronts, customers.",
  },
  {
    value: ROLES.FINANCE_ADMIN,
    label: "Finance Admin",
    description:
      "Handles payouts, commissions, refunds, and wallet adjustments.",
  },
  {
    value: ROLES.SUPPORT_ADMIN,
    label: "Support Admin",
    description:
      "Manages tickets, customer notifications, and support workflows.",
  },
  {
    value: ROLES.SERVICE_ADMIN,
    label: "Service Admin",
    description: "Owns the service catalogue, providers, and pricing.",
  },
  {
    value: ROLES.ANALYST,
    label: "Analyst",
    description: "Read-only across the platform with export permissions.",
  },
  {
    value: ROLES.VIEWER,
    label: "Viewer",
    description: "Read-only access to accounts and dashboards.",
  },
];

const OPERATIONS: Permission[] = [
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.CUSTOMERS_EDIT,
  PERMISSIONS.CUSTOMERS_SUSPEND,
  PERMISSIONS.CUSTOMERS_NOTIFY,
  PERMISSIONS.RESELLERS_VIEW,
  PERMISSIONS.RESELLERS_EDIT,
  PERMISSIONS.RESELLERS_SUSPEND,
  PERMISSIONS.RESELLERS_VERIFY,
  PERMISSIONS.RESELLERS_TIER,
  PERMISSIONS.RESELLERS_STOREFRONT_TOGGLE,
  PERMISSIONS.RESELLERS_NOTIFY,
  PERMISSIONS.RESELLERS_WITHDRAWALS_APPROVE,
  PERMISSIONS.MERCHANTS_VIEW,
  PERMISSIONS.MERCHANTS_EDIT,
  PERMISSIONS.MERCHANTS_SUSPEND,
  PERMISSIONS.MERCHANTS_STORE_TOGGLE,
  PERMISSIONS.MERCHANTS_NOTIFY,
  PERMISSIONS.STOREFRONT_USERS_VIEW,
  PERMISSIONS.STOREFRONT_USERS_SUSPEND,
  PERMISSIONS.STOREFRONT_USERS_NOTIFY,
  PERMISSIONS.STOREFRONT_USERS_REVEAL_PII,
  PERMISSIONS.STOREFRONT_USERS_SEGMENT,
  PERMISSIONS.STOREFRONT_USERS_TAG,
  PERMISSIONS.STOREFRONT_USERS_EXPORT,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.ORDERS_MANAGE,
  PERMISSIONS.TRANSACTIONS_VIEW,
  PERMISSIONS.TRANSACTIONS_RETRY,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.REFUNDS_VIEW,
  PERMISSIONS.REFUNDS_APPROVE,
  PERMISSIONS.REFUNDS_REJECT,
  PERMISSIONS.SERVICES_VIEW,
  PERMISSIONS.SERVICES_MANAGE,
  PERMISSIONS.DATA_PLANS_VIEW,
  PERMISSIONS.DATA_PLANS_MANAGE,
  PERMISSIONS.PROVIDERS_VIEW,
  PERMISSIONS.PROVIDERS_MANAGE,
  PERMISSIONS.STOREFRONTS_VIEW,
  PERMISSIONS.STOREFRONTS_MANAGE,
  PERMISSIONS.ANALYTICS_VIEW,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.EXPORT,
  PERMISSIONS.DOMAINS_VIEW,
  PERMISSIONS.DOMAINS_MANAGE,
  PERMISSIONS.TEMPLATES_VIEW,
  PERMISSIONS.TEMPLATES_MANAGE,
  PERMISSIONS.SUBSCRIPTIONS_VIEW,
  PERMISSIONS.SUBSCRIPTIONS_MANAGE,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.ECOMMERCE_PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_RECONCILE,
  PERMISSIONS.PAYMENTS_FLAG,
  PERMISSIONS.TREASURY_VIEW,
];

const FINANCE: Permission[] = [
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.CUSTOMERS_WALLET,
  PERMISSIONS.RESELLERS_VIEW,
  PERMISSIONS.RESELLERS_WALLET,
  PERMISSIONS.RESELLERS_WALLET_CONFIG,
  PERMISSIONS.WALLETS_VIEW,
  PERMISSIONS.WALLETS_ADJUST,
  PERMISSIONS.WALLETS_WITHDRAWALS_APPROVE,
  PERMISSIONS.WALLETS_CONFIG,
  PERMISSIONS.PAYMENTS_RECONCILE,
  PERMISSIONS.PAYMENTS_FLAG,
  PERMISSIONS.RESELLERS_WITHDRAWALS_APPROVE,
  PERMISSIONS.MERCHANTS_VIEW,
  PERMISSIONS.MERCHANTS_PLAN,
  PERMISSIONS.MERCHANTS_CONTRACT_MRR,
  PERMISSIONS.STOREFRONT_USERS_VIEW,
  PERMISSIONS.STOREFRONT_USERS_EXPORT,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.TRANSACTIONS_VIEW,
  PERMISSIONS.TRANSACTIONS_EXPORT,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_EXPORT,
  PERMISSIONS.PAYMENTS_REFUND,
  PERMISSIONS.REFUNDS_VIEW,
  PERMISSIONS.REFUNDS_APPROVE,
  PERMISSIONS.REFUNDS_REJECT,
  PERMISSIONS.REFUNDS_PROCESS,
  PERMISSIONS.WALLETS_VIEW,
  PERMISSIONS.WALLETS_ADJUST,
  PERMISSIONS.COMMISSIONS_VIEW,
  PERMISSIONS.COMMISSIONS_MANAGE,
  PERMISSIONS.SERVICES_VIEW,
  PERMISSIONS.DATA_PLANS_VIEW,
  PERMISSIONS.ANALYTICS_VIEW,
  PERMISSIONS.ANALYTICS_EXPORT,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.AUDIT_LOGS_VIEW,
  PERMISSIONS.AUDIT_LOGS_EXPORT,
  PERMISSIONS.EXPORT,
  PERMISSIONS.SUBSCRIPTIONS_VIEW,
  PERMISSIONS.SUBSCRIPTIONS_MANAGE,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_EXPORT,
  PERMISSIONS.PAYMENTS_REFUND,
  PERMISSIONS.PAYMENTS_WITHDRAWALS_APPROVE,
  PERMISSIONS.PAYMENTS_CONFIG,
  PERMISSIONS.ECOMMERCE_PAYMENTS_VIEW,
  PERMISSIONS.TREASURY_VIEW,
  PERMISSIONS.TREASURY_MANAGE,
  PERMISSIONS.TREASURY_APPROVE,
  PERMISSIONS.TREASURY_FUND,
];

const SUPPORT: Permission[] = [
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.CUSTOMERS_NOTIFY,
  PERMISSIONS.RESELLERS_VIEW,
  PERMISSIONS.RESELLERS_NOTIFY,
  PERMISSIONS.MERCHANTS_VIEW,
  PERMISSIONS.MERCHANTS_NOTIFY,
  PERMISSIONS.STOREFRONT_USERS_VIEW,
  PERMISSIONS.STOREFRONT_USERS_NOTIFY,
  PERMISSIONS.STOREFRONT_USERS_REVEAL_PII,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.TRANSACTIONS_VIEW,
  PERMISSIONS.TRANSACTIONS_RETRY,
  PERMISSIONS.REFUNDS_VIEW,
  PERMISSIONS.SUPPORT_VIEW,
  PERMISSIONS.SUPPORT_MANAGE,
  PERMISSIONS.NOTIFICATIONS_VIEW,
  PERMISSIONS.SERVICES_VIEW,
  PERMISSIONS.DATA_PLANS_VIEW,
  PERMISSIONS.MERCHANTS_VIEW,
  PERMISSIONS.MERCHANTS_NOTIFY,
  PERMISSIONS.ECOMMERCE_PAYMENTS_VIEW,
  PERMISSIONS.PAYMENTS_FLAG,
];

const SERVICE: Permission[] = [
  PERMISSIONS.SERVICES_VIEW,
  PERMISSIONS.SERVICES_MANAGE,
  PERMISSIONS.DATA_PLANS_VIEW,
  PERMISSIONS.DATA_PLANS_MANAGE,
  PERMISSIONS.PROVIDERS_VIEW,
  PERMISSIONS.PROVIDERS_MANAGE,
  PERMISSIONS.PRICING_VIEW,
  PERMISSIONS.PRICING_MANAGE,
  PERMISSIONS.STOREFRONTS_VIEW,
  PERMISSIONS.STOREFRONTS_MANAGE,
  PERMISSIONS.ANALYTICS_VIEW,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.DOMAINS_VIEW,
  PERMISSIONS.DOMAINS_MANAGE,
  PERMISSIONS.TEMPLATES_VIEW,
  PERMISSIONS.TEMPLATES_MANAGE,
  PERMISSIONS.SUBSCRIPTIONS_VIEW,
  PERMISSIONS.SUBSCRIPTIONS_MANAGE,
];

const ANALYST: Permission[] = [
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.RESELLERS_VIEW,
  PERMISSIONS.MERCHANTS_VIEW,
  PERMISSIONS.STOREFRONT_USERS_VIEW,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.TRANSACTIONS_VIEW,
  PERMISSIONS.PAYMENTS_VIEW,
  PERMISSIONS.ECOMMERCE_PAYMENTS_VIEW,
  PERMISSIONS.WALLETS_VIEW,
  PERMISSIONS.COMMISSIONS_VIEW,
  PERMISSIONS.SERVICES_VIEW,
  PERMISSIONS.DATA_PLANS_VIEW,
  PERMISSIONS.PROVIDERS_VIEW,
  PERMISSIONS.ANALYTICS_VIEW,
  PERMISSIONS.ANALYTICS_EXPORT,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.REPORTS_EXPORT,
  PERMISSIONS.AUDIT_LOGS_VIEW,
  PERMISSIONS.AUDIT_LOGS_EXPORT,
  PERMISSIONS.EXPORT,
  PERMISSIONS.DOMAINS_VIEW,
  PERMISSIONS.TEMPLATES_VIEW,
  PERMISSIONS.TREASURY_VIEW,
];

const VIEWER: Permission[] = [
  PERMISSIONS.CUSTOMERS_VIEW,
  PERMISSIONS.RESELLERS_VIEW,
  PERMISSIONS.MERCHANTS_VIEW,
  PERMISSIONS.STOREFRONT_USERS_VIEW,
  PERMISSIONS.ORDERS_VIEW,
  PERMISSIONS.TRANSACTIONS_VIEW,
  PERMISSIONS.SERVICES_VIEW,
  PERMISSIONS.DATA_PLANS_VIEW,
  PERMISSIONS.ANALYTICS_VIEW,
  PERMISSIONS.REPORTS_VIEW,
  PERMISSIONS.DOMAINS_VIEW,
  PERMISSIONS.TEMPLATES_VIEW,
];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.OPERATIONS_ADMIN]: OPERATIONS,
  [ROLES.FINANCE_ADMIN]: FINANCE,
  [ROLES.SUPPORT_ADMIN]: SUPPORT,
  [ROLES.SERVICE_ADMIN]: SERVICE,
  [ROLES.ANALYST]: ANALYST,
  [ROLES.VIEWER]: VIEWER,
};

export function roleLabel(role: Role): string {
  return ALL_ROLES.find((r) => r.value === role)?.label ?? role;
}

export function roleDescription(role: Role): string {
  return ALL_ROLES.find((r) => r.value === role)?.description ?? "";
}

export function rolePermissions(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}